// booking.model.ts

export interface Booking {
    bookingId?: number; // Optional if using for POST requests (auto-generated by backend)
    userId: number;
    scheduleId: number; // Correct type definition for scheduleId
    seatNumbers: string;
    bookingDate: string;
    totalFare: string;
    status: string;
  }
  