// src/app/user.model.ts

export interface User {
    userId?: number; // Optional if using for POST requests (auto-generated by backend)
    name: string;
    email: string;
    password: string;
    phoneNumber: string;
    address: string;
  }
  